### ISSUE TITLE
tekton-pipelines-controller Deployment references non-existent gsutil image

### ISSUE THREAD

**Issue by ron1** [openshift/tektoncd-pipeline-operator#239]
The tekton-pipelines-controller Deployment generated by the operator specifies invalid gsutil-image  quay.io/openshift-pipeline/tektoncd-pipeline-gsutil:v0.10.1. The only relevant tag in quay.io is v0.8.0 not v0.10.1. Based on PR https://github.com/openshift/tektoncd-pipeline/pull/209/files, is it possible this image is no longer used?

**Comment by chmouel** [comment]
indeed, I removed it in here : 

https://github.com/tektoncd/pipeline/commit/f1692b9aaa688bbe0b666b4414df88f47237f728

Since upstream (ie pipeline) is not generating a binary wrapper anymore but using the `google/cloud-sdk` image directly.. 

I think in the mean time until we get this fixed you can update your deployment referencing this image directly...

@nikhil-thomas I have created https://github.com/openshift/tektoncd-pipeline/pull/328 which would be used for next release, we can backport this to the release.yaml if you think so ? or wait for next release?

**Comment by ckadner** [comment]
@chmouel @nikhil-thomas did you make any progress on resolving this issue?
